schema_version = "0.2"
name = "ato-zero-config-e2e-20260218184323"
description = "Koh0920/ato-zero-config-e2e-20260218184323"
type = "app"
default_target = "app"

[targets.app]
runtime = "source"
entrypoint = "run.sh"

[metadata]
store_icon = "https://stg-assets.ato.run/capsules/01KHS0MC9WM4KD7BX0QVDPHNRJ/draft-assets/01KHS0MCRWCWREVB35XJW19K4V.png"
store_cover_image = "https://stg-assets.ato.run/capsules/01KHS0MC9WM4KD7BX0QVDPHNRJ/draft-assets/01KHS0MCENQJSJ0MEG078X9ZDK.png"
